In [1]:
import numpy as np

* Faster and easier, and more visual then looping throug things

* What is the last problem

* Mainly for linear 

### generating an array with numpy

In [47]:
full_array = np.full((3, 6, 5), range(2, 12, 2))

In [64]:
n_array = np.arange(1, 5)

In [67]:
n_array[1]

2

In [ ]:
### know the location in memory of the starting of n_array
# 7654
# 7661
# 7668



In [69]:
type(n_array.astype('<U21')[0])

numpy.str_

In [66]:
np.append(np.arange(1, 5), '1')

array(['1', '2', '3', '4', '1'], dtype='<U21')

In [20]:
np.random.normal(0, .5)

0.10109705998285198

In [71]:
str(121221)

'121221'

In [46]:
grid = np.indices((2, 3))
grid

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

### Retrieving Data

In [73]:
full_array = np.full((6, 5), range(2, 12, 2))

In [77]:
full_array

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [98]:
np.append(full_array, np.arange(1, 6)).shape

(35,)

In [108]:
tuple([35])

(35,)

In [112]:
np.arange(1, 4)

array([1, 2, 3])

In [110]:
np.append(full_array, np.arange(1, 11)).reshape(40, 1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [118]:
my_matrix = full_array.reshape(5, 6)

In [119]:
my_matrix

array([[ 2,  4,  6,  8, 10,  2],
       [ 4,  6,  8, 10,  2,  4],
       [ 6,  8, 10,  2,  4,  6],
       [ 8, 10,  2,  4,  6,  8],
       [10,  2,  4,  6,  8, 10]])

In [122]:
3 % 2 == 0

False

In [125]:
matrix_of_booleans = my_matrix % 4 == 0

In [127]:
my_matrix

array([[ 2,  4,  6,  8, 10,  2],
       [ 4,  6,  8, 10,  2,  4],
       [ 6,  8, 10,  2,  4,  6],
       [ 8, 10,  2,  4,  6,  8],
       [10,  2,  4,  6,  8, 10]])

In [139]:
my_matrix[:, 1] == 4

array([ True, False, False, False, False])

In [138]:
my_matrix[]

array([], shape=(0, 5, 6), dtype=int64)

In [126]:
matrix_of_booleans

array([[False,  True, False,  True, False, False],
       [ True, False,  True, False, False,  True],
       [False,  True, False, False,  True, False],
       [ True, False, False,  True, False,  True],
       [False, False,  True, False,  True, False]])

In [133]:
my_matrix[my_matrix % 4 == 0]

array([4, 8, 4, 8, 4, 8, 4, 8, 4, 8, 4, 8])

In [78]:
full_array.shape

(6, 5)

### Work with Wikipedia chart


In [2]:
list_of_msas = 'https://en.wikipedia.org/wiki/List_of_metropolitan_statistical_areas'

In [50]:
import pandas as pd

In [51]:
msa_df = pd.read_html(list_of_msas)[1]

In [52]:
msa_npa = msa_df
array = msa_npa.values

In [53]:
my_table = array[1:]

In [94]:
places = np.array([array[1] for array in my_table])
estimates2017 = np.array([int(array[2]) for array in my_table])
estimates2010 = np.array([int(array[3]) for array in my_table])
pop_diff = estimates2017 - estimates2010 # population difference from 2010 -2017
percent_change = np.array([array[4] for array in my_table])


In [73]:
import plotly.offline as py
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode

import pandas_datareader as web
init_notebook_mode(connected = True)

In [84]:
data = [go.Bar(x = places[:20], y = pop_diff[:20])]
layout = go.Layout(title = 'Population Difference from 2010-2017 of top 20 Cities')
fig = go.Figure(data = data, layout = layout)

py.iplot(fig)

### Work with President data

In [131]:
import collections

presidents = pd.read_csv('presidents.csv').values
pres = [president[1:] for president in presidents]
names = [pre[0] for pre in np.array(pres)]
heights = [pre[1] for pre in np.array(pres)]

n = np.array(names)
h = np.array(heights)
counter = collections.Counter(h)
data = [go.Bar(x = list(counter.keys()), y = list(counter.values()))]
layout = go.Layout(title = 'Frequency of heights ')
fig = go.Figure(data = data, layout = layout)

py.iplot(fig)

In [165]:
feet_conv = h/30.48
frac,feet = np.modf(feet_conv)
inch = frac*12
inches = np.around(inch)
feet

array([6., 5., 6., 5., 6., 5., 6., 5., 5., 6., 5., 5., 5., 5., 6., 6., 5.,
       5., 5., 6., 6., 5., 5., 5., 5., 5., 6., 5., 5., 6., 5., 5., 6., 6.,
       5., 6., 5., 6., 6., 6., 5., 6.])

In [164]:
np.where(feet < 6)

(array([ 1,  3,  5,  7,  8, 10, 11, 12, 13, 16, 17, 18, 21, 22, 23, 24, 25,
        27, 28, 30, 31, 34, 36, 40]),)

### Work with ESPN data

In [167]:
box_score = 'http://www.espn.com/nba/boxscore?gameId=401070872'

In [178]:
seventy6ers = pd.read_html(box_score)[1]
heat = pd.read_html(box_score)[2]

In [181]:
seventy6ers

Starters                   MIN     FG    3PT     FT  \
0         W. ChandlerW. ChandlerSF                    23    2-3    1-1    0-0   
1              J. EmbiidJ. EmbiidC                    36   8-15    3-4  16-20   
2           B. SimmonsB. SimmonsPG                    35    5-7    0-0    3-4   
3               M. FultzM. FultzPG                    25    2-8    0-0    1-3   
4             J. RedickJ. RedickSG                    31  11-20    3-9    0-0   
5           M. MuscalaM. MuscalaPF                    27   3-11   3-10    4-5   
6            A. JohnsonA. JohnsonC                     2    0-1    0-0    0-0   
7             L. ShametL. ShametPG                    24    3-5    2-4    2-2   
8   T.J. McConnellT.J. McConnellPG                    14    0-4    0-2    2-2   
9           F. KorkmazF. KorkmazSG                    22    5-9    3-6    3-3   
10            J. BoldenJ. BoldenPF  DNP-COACH'S DECISION    NaN    NaN    NaN   
11          D. JacksonD. JacksonPG  DNP-COACH'S DECISION    NaN    NaN    NaN   
12            S. MiltonS. MiltonSG  DNP-COACH'S DECISION    NaN    NaN    NaN   
13                            TEAM                   NaN  39-83  15-36  31-39   
14                             NaN                   NaN  47.0%  41.7%  79.5%   

    OREB  DREB   REB   AST  STL  BLK   TO    PF   +/-    PTS  
0    1.0   0.0   1.0   3.0  1.0  0.0  2.0   2.0   6.0    5.0  
1    6.0  12.0  18.0   3.0  0.0  0.0  2.0   1.0  12.0   35.0  
2    2.0   5.0   7.0   7.0  1.0  0.0  4.0   0.0  20.0   13.0  
3    0.0   2.0   2.0   5.0  0.0  0.0  0.0   2.0  -7.0    5.0  
4    0.0   1.0   1.0   3.0  0.0  0.0  1.0   4.0  11.0   25.0  
5    0.0   8.0   8.0   1.0  0.0  0.0  0.0   4.0   4.0   13.0  
6    0.0   0.0   0.0   1.0  0.0  0.0  0.0   1.0   2.0    0.0  
7    0.0   0.0   0.0   1.0  0.0  0.0  0.0   4.0  10.0   10.0  
8    0.0   1.0   1.0   0.0  2.0  0.0  0.0   1.0 -15.0    2.0  
9    1.0   3.0   4.0   0.0  1.0  0.0  0.0   5.0   7.0   16.0  
10   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN    NaN  
11   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN    NaN  
12   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN    NaN  
13  10.0  32.0  42.0  24.0  5.0  0.0  9.0  24.0   NaN  124.0  
14   NaN   NaN   NaN   NaN  NaN  NaN  NaN   NaN   NaN    NaN

### Resources

In [15]:
box_score = 'http://www.espn.com/nba/boxscore?gameId=401070872'

list_of_msas = 'https://en.wikipedia.org/wiki/List_of_metropolitan_statistical_areas'

* presidential heights